version: '3'
services:
  spn-node:
    container_name: SPN_Community_Node
    image: dockerteun/spn-community-node:latest
    ports:
      - 80
      - 17
    environment:
      - name=value            # REQUIRED Set the name of the node.
    #  - group=value           # OPTIONAL Person or organisation, who is in control of the node (should be same for all nodes of this person or organisation).
    #  - contactAddress=value  # OPTIONAL Contact possibility (recommended, but optional).
    #  - contactService=value  # OPTIONAL Type of service of the contact address, if not email.
      - hosters=Community     # REQUIRED Hosters - supply chain (reseller, hosting provider, datacenter operator, …).
    #  - datacenter=value      # OPTIONAL Datacenter in the format of COUNTRYCODE-COMPANY-INTERNALCODE (eg: DE-Hetzner-FSN1-DC5)
      - ip4=value             # REQUIRED IPv4 address must be global and accessible.
    #  - ip6=value             # OPTIONAL IPv6 address must be global and accessible.
    #  - transports=value      # OPTIONAL Define available protocols for communicating with other nodes and clients. Leave undefined to use defaults.
    #  - entry=value           # OPTIONAL Set an entry policy (for clients) with the same syntax as rules.
    #  - exit=value            # OPTIONAL Set an exit policy (for destinations) with the same syntax as rules. The default is to block TCP/25 (SMTP) traffic.
    #  - METRICS_COMMENT       # OPTIONAL Set an comment for the metricscollection?!